name: "PyInstaller Poetry"
description: "Package python app as executable using poetry to install dependencies."
inputs:
  path:
    description: "Directory containing pyproject.toml & .spec file."
    required: False
    default: .
  spec:
    description: "Specify a file path for .spec file"
    required: False
    default: "pyinstaller.spec"
  out_dir:
    description: "Output directory for installed app."
    required: False
    default: "dist/linux"
  pre_package_hook:
    description: "bash code to execute before pyinstaller."
    required: False
    default: ""
outputs:
  output:
    description: "Pyinstaller Output"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.spec }}
    - ${{ inputs.out_dir }}
    - ${{ inputs.pre_package_hook }}
